services:
  calculator:
    image: registry.yurii.live/erep-calculator:latest
    container_name: erep-calculator
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - ./data:/data
    environment:
      - PORT=8080
      - DATA_DIR=/data
