// GENERATED by scripts/gen-i18n-resources.mjs — do not edit by hand.
// Only the 25 flags actually used are imported (as Vite asset URLs),
// instead of shipping the full flag-icons world-sprite CSS.
import fi_al from 'flag-icons/flags/4x3/al.svg';
import fi_bg from 'flag-icons/flags/4x3/bg.svg';
import fi_by from 'flag-icons/flags/4x3/by.svg';
import fi_cn from 'flag-icons/flags/4x3/cn.svg';
import fi_de from 'flag-icons/flags/4x3/de.svg';
import fi_es from 'flag-icons/flags/4x3/es.svg';
import fi_fr from 'flag-icons/flags/4x3/fr.svg';
import fi_gb from 'flag-icons/flags/4x3/gb.svg';
import fi_gr from 'flag-icons/flags/4x3/gr.svg';
import fi_hr from 'flag-icons/flags/4x3/hr.svg';
import fi_hu from 'flag-icons/flags/4x3/hu.svg';
import fi_id from 'flag-icons/flags/4x3/id.svg';
import fi_ir from 'flag-icons/flags/4x3/ir.svg';
import fi_it from 'flag-icons/flags/4x3/it.svg';
import fi_jp from 'flag-icons/flags/4x3/jp.svg';
import fi_kr from 'flag-icons/flags/4x3/kr.svg';
import fi_mk from 'flag-icons/flags/4x3/mk.svg';
import fi_pl from 'flag-icons/flags/4x3/pl.svg';
import fi_pt from 'flag-icons/flags/4x3/pt.svg';
import fi_ro from 'flag-icons/flags/4x3/ro.svg';
import fi_rs from 'flag-icons/flags/4x3/rs.svg';
import fi_sk from 'flag-icons/flags/4x3/sk.svg';
import fi_tr from 'flag-icons/flags/4x3/tr.svg';
import fi_tw from 'flag-icons/flags/4x3/tw.svg';
import fi_ua from 'flag-icons/flags/4x3/ua.svg';

export const FLAG_URL: Record<string, string> = {
  al: fi_al,
  bg: fi_bg,
  by: fi_by,
  cn: fi_cn,
  de: fi_de,
  es: fi_es,
  fr: fi_fr,
  gb: fi_gb,
  gr: fi_gr,
  hr: fi_hr,
  hu: fi_hu,
  id: fi_id,
  ir: fi_ir,
  it: fi_it,
  jp: fi_jp,
  kr: fi_kr,
  mk: fi_mk,
  pl: fi_pl,
  pt: fi_pt,
  ro: fi_ro,
  rs: fi_rs,
  sk: fi_sk,
  tr: fi_tr,
  tw: fi_tw,
  ua: fi_ua,
};
